N_bin: 100
N_zombies_per_bin: 10000
Npsr_min: 2
PTA_config: SKA-130-noRN-nogaps
SNR_thresh: 3
bounds:
  log10_Mcr_max: 11
  log10_Mcr_min: 7.5
  logz: true
  z_max: 4.1
  z_min: 0.01
chunk_size: 10000
evolve: true
fth: 3.0e-07
hc_ref: 3.0e-15
seed: 42
toas_thin_factor: 1

